// Current time tone
// 0 = Morning
// 1 = Noon
// 2 = Sunset
// 3 = Night

// AI Usage Instructions: This section of code was generated by AI assistance to achieve a smooth transition between colors, rather than jumping directly to the next color each time.
let toneValue = 2;

// AI Usage Instructions: This section of code was generated by AI assistance. It is used to record the state of long-pressing the direction keys and to achieve the function of continuously changing colors.
let toneHoldDirection = 0;


// AI Usage Instructions: This section of code was generated with the assistance of AI and is used to calculate the rate of color change.
let lastToneUpdateTime = 0;



// AI Usage Instructions: This section of code was generated with the assistance of AI to control the speed of color changes when the direction key is pressed for a long time.
let toneChangeSpeed = 0.45;

// Four time-tone palettes
// AI usage note: AI was consulted for the code-writing format of a nested structure:
// an array containing objects, and each object containing a colors object.
// This part is used to store four groups of time-tone colors.
let timeTonePalettes = [
  {
    name: "Morning",
    colors: {
      skyBlue: [178, 205, 238],
      darkBlue: [92, 132, 168],
      oceanBlue: [145, 192, 222],
      softOrange: [238, 214, 228],
      goldenOrange: [248, 198, 188],
      pinkPurple: [206, 188, 224],
      sunYellow: [255, 242, 205],
      foamGrey: [190, 210, 236],
      creamYellow: [255, 235, 220]
    }
  },
  {
    name: "Noon",
    colors: {
      skyBlue: [105, 220, 246],
      darkBlue: [20, 130, 170],
      oceanBlue: [48, 200, 225],
      softOrange: [238, 252, 255],
      goldenOrange: [255, 235, 135],
      pinkPurple: [175, 218, 245],
      sunYellow: [255, 252, 215],
      foamGrey: [212, 245, 255],
      creamYellow: [255, 255, 235]
    }
  },
  {
    name: "Sunset",
    colors: {
      skyBlue: [146, 178, 221],
      darkBlue: [65, 93, 137],
      oceanBlue: [103, 142, 182],
      softOrange: [241, 186, 112],
      goldenOrange: [235, 145, 84],
      pinkPurple: [180, 120, 175],
      sunYellow: [255, 238, 160],
      foamGrey: [180, 180, 220],
      creamYellow: [250, 220, 190]
    }
  },
  {
    name: "Night",
    colors: {
      skyBlue: [22, 34, 95],
      darkBlue: [5, 14, 45],
      oceanBlue: [8, 35, 72],
      softOrange: [35, 32, 95],
      goldenOrange: [45, 65, 130],
      pinkPurple: [48, 44, 118],
      sunYellow: [170, 220, 230],
      foamGrey: [58, 82, 145],
      creamYellow: [140, 210, 230]
    }
  }
];


// draw()
function drawUserInput() {

// AI Usage Instructions: This section of code was generated with the assistance of AI and is used to continuously update the color transition state in each frame.
  updateToneChange();

  background(250, 240, 235);

  drawToneSkyBackground();
  drawToneOceanBackground();

  drawToneWarmSkyBase();
  drawToneWarmOceanBase();
  drawToneSunGlow();

  drawToneSkyOverlap();
  drawToneOceanOverlap();
}



// AI Usage Instructions: This section of code was generated by AI assistance to achieve the function of continuously changing the color by long-pressing the left/right arrow keys.
function keyPressed() {
  if (keyCode == RIGHT_ARROW) {
    toneHoldDirection = 1;
    lastToneUpdateTime = millis();
    return false;
  }

  if (keyCode == LEFT_ARROW) {
    toneHoldDirection = -1;
    lastToneUpdateTime = millis();
    return false;
  }
}



// AI Usage Instructions: This section of code was generated by AI assistance and is used to implement the function of stopping the color change when the left/right arrow keys are released.
function keyReleased() {
  if (keyCode == RIGHT_ARROW) {
    toneHoldDirection = 0;
    return false;
  }

  if (keyCode == LEFT_ARROW) {
    toneHoldDirection = 0;
    return false;
  }
}



// AI Usage Instructions: This section of code was generated by AI assistance. It is used to continuously update the toneValue based on the long press direction and elapsed time, thereby achieving a more natural color change.
function updateToneChange() {
  if (toneHoldDirection == 0) {
    lastToneUpdateTime = millis();
    return;
  }

  let now = millis();

  let deltaTime = (now - lastToneUpdateTime) / 1000;

  lastToneUpdateTime = now;

  toneValue = toneValue + toneHoldDirection * toneChangeSpeed * deltaTime;

  toneValue = wrapToneValue(toneValue);
}



// AI Usage Instructions: This section of code was generated with the assistance of AI to enable toneValue to cycle through the four different time tones.
function wrapToneValue(value) {
  let total = timeTonePalettes.length;

  while (value < 0) {
    value = value + total;
  }

  while (value >= total) {
    value = value - total;
  }

  return value;
}



// AI Usage Instructions: This section of code was generated by AI assistance and is used to achieve a smooth color transition between different time tones by utilizing Math.floor(), %, and lerp().
function getToneColor(colorName) {
  let total = timeTonePalettes.length;

  let fromIndex = Math.floor(toneValue);
  let toIndex = (fromIndex + 1) % total;

  let amount = toneValue - fromIndex;

  let fromRGB = timeTonePalettes[fromIndex].colors[colorName];
  let toRGB = timeTonePalettes[toIndex].colors[colorName];

  if (fromRGB == undefined) {
    return color(0);
  }

  if (toRGB == undefined) {
    return color(0);
  }

  let r = lerp(fromRGB[0], toRGB[0], amount);
  let g = lerp(fromRGB[1], toRGB[1], amount);
  let b = lerp(fromRGB[2], toRGB[2], amount);

  return color(r, g, b);
}

// This part directly follows and adapts the code structure from sketch.js
// First layer: sky background
function drawToneSkyBackground() {
  let horizonY = height * horizonLine;

  for (let segment of segmentArr) {
    let cy = segment.y + segment.height / 2;

    if (cy < horizonY) {
      noStroke();
      fill(getToneColor("skyBlue"));
      rect(segment.x, segment.y, segment.width, segment.height);
    }
  }
}



// First layer: ocean background
function drawToneOceanBackground() {
  let horizonY = height * horizonLine;

  for (let segment of segmentArr) {
    let cy = segment.y + segment.height / 2;

    if (cy >= horizonY) {
      noStroke();
      fill(getToneColor("oceanBlue"));
      rect(segment.x, segment.y, segment.width, segment.height);
    }
  }
}



// Second layer: warm sky layer
function drawToneWarmSkyBase() {
  let horizonY = height * horizonLine;

  noStroke();
  fill(getToneColor("softOrange"));

  for (let segment of segmentArr) {
    let cy = segment.y + segment.height / 2;

    if (cy < horizonY) {
      if (segment.colorName != "skyBlue") {
        rect(segment.x, segment.y, segment.width, segment.height);
      }
    }
  }
}



// Second layer: warm ocean reflection
function drawToneWarmOceanBase() {
  let horizonY = height * horizonLine;

  noStroke();
  fill(getToneColor("softOrange"));

  for (let segment of segmentArr) {
    let cy = segment.y + segment.height / 2;

    if (cy >= horizonY) {
      if (segment.colorName == "goldenOrange") {
        rect(segment.x, segment.y, segment.width, segment.height);
      }
    }
  }
}



// Second layer: highlight dots near the sun
function drawToneSunGlow() {
  let horizonY = height * horizonLine;
  let sunCentreX = width / 2;
  let sunRange = width * 0.15;

  for (let segment of segmentArr) {
    let cx = segment.x + segment.width / 2;
    let cy = segment.y + segment.height / 2;

    let nearSun = false;

    if (abs(cx - sunCentreX) < sunRange) {
      if (cy > horizonY * 0.7) {
        if (cy < horizonY) {
          nearSun = true;
        }
      }
    }

    if (nearSun == true) {
      if (segment.colorName == "softOrange") {
        drawFourDotsWithColor(segment, getToneColor("creamYellow"));
      } else if (segment.colorName == "sunYellow") {
        drawFourDotsWithColor(segment, getToneColor("creamYellow"));
      } else if (segment.colorName == "creamYellow") {
        drawFourDotsWithColor(segment, getToneColor("creamYellow"));
      }
    }
  }
}



// Third layer: sky patterns
function drawToneSkyOverlap() {
  let horizonY = height * horizonLine;

  for (let segment of segmentArr) {
    let cy = segment.y + segment.height / 2;

    if (cy < horizonY) {
      if (segment.colorName == "goldenOrange") {
        drawCrossWithColor(segment, getToneColor("goldenOrange"));
      } else if (segment.colorName == "pinkPurple") {
        drawHorizontalLinesWithColor(segment, getToneColor("pinkPurple"));
      } else if (segment.colorName == "sunYellow") {
        noStroke();
        fill(getToneColor("sunYellow"));
        rect(segment.x, segment.y, segment.width, segment.height);
      }
    }
  }
}



// Third layer: ocean patterns
function drawToneOceanOverlap() {
  let horizonY = height * horizonLine;

  for (let segment of segmentArr) {
    let cy = segment.y + segment.height / 2;

    if (cy >= horizonY) {
      if (segment.colorName == "darkBlue") {
        drawCrossWithColor(segment, getToneColor("darkBlue"));
      } else if (segment.colorName == "skyBlue") {
        drawReflectionLinesWithColor(segment, getToneColor("skyBlue"));
      } else if (segment.colorName == "softOrange") {
        noStroke();
        fill(getToneColor("softOrange"));
        rect(segment.x, segment.y, segment.width, segment.height);
      } else if (segment.colorName == "goldenOrange") {
        drawCrossWithColor(segment, getToneColor("goldenOrange"));
      } else if (segment.colorName == "pinkPurple") {
        drawReflectionLinesWithColor(segment, getToneColor("pinkPurple"));
      } else if (segment.colorName == "sunYellow") {
        drawReflectionLinesWithColor(segment, getToneColor("sunYellow"));
      } else if (segment.colorName == "foamGrey") {
        drawSmallerSquareWithColor(segment, getToneColor("foamGrey"));
      } else if (segment.colorName == "creamYellow") {
        drawSmallDotWithColor(segment, getToneColor("creamYellow"));
      }
    }
  }
}



// Basic shape functions with color parameters
function drawSmallerSquareWithColor(segment, c) {
  let x = segment.x;
  let y = segment.y;
  let w = segment.width;
  let h = segment.height;

  noStroke();
  fill(c);
  rect(x + w * 0.18, y + h * 0.18, w * 0.64, h * 0.64);
}


function drawFourDotsWithColor(segment, dotColor) {
  let x = segment.x;
  let y = segment.y;
  let w = segment.width;
  let h = segment.height;

  noStroke();
  fill(dotColor);

  let dotSize = w * 0.3;
  let left = x + w * 0.3;
  let right = x + w * 0.7;
  let top = y + h * 0.3;
  let bottom = y + h * 0.7;

  circle(left, top, dotSize);
  circle(right, top, dotSize);
  circle(left, bottom, dotSize);
  circle(right, bottom, dotSize);
}


function drawSmallDotWithColor(segment, c) {
  let x = segment.x;
  let y = segment.y;
  let w = segment.width;
  let h = segment.height;

  noStroke();
  fill(c);
  circle(x + w / 2, y + h / 2, w * 0.36);
}


function drawCrossWithColor(segment, c) {
  let x = segment.x;
  let y = segment.y;
  let w = segment.width;
  let h = segment.height;

  stroke(c);
  strokeWeight(2);

  line(x + w * 0.25, y + h * 0.5, x + w * 0.75, y + h * 0.5);
  line(x + w * 0.5, y + h * 0.25, x + w * 0.5, y + h * 0.75);
}


function drawHorizontalLinesWithColor(segment, c) {
  let x = segment.x;
  let y = segment.y;
  let w = segment.width;
  let h = segment.height;

  stroke(c);
  strokeWeight(1);

  line(x + w * 0.16, y + h * 0.3, x + w * 0.84, y + h * 0.3);
  line(x + w * 0.16, y + h * 0.5, x + w * 0.84, y + h * 0.5);
  line(x + w * 0.16, y + h * 0.7, x + w * 0.84, y + h * 0.7);
}


function drawReflectionLinesWithColor(segment, c) {
  let x = segment.x;
  let y = segment.y;
  let w = segment.width;
  let h = segment.height;

  stroke(c);
  strokeWeight(1);

  line(x + w * 0.18, y + h * 0.38, x + w * 0.82, y + h * 0.38);
  line(x + w * 0.18, y + h * 0.62, x + w * 0.82, y + h * 0.62);
}